service: aws-iaas-fil-rouge

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7 # or python3.7, supported as of November 2018
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::iaas-projetfilrouge-pdesmarc/*"

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app
    packRequirements: false

functions:
  app:
    handler: wsgi.handler
    events:
      - http:
          path: transform
          method: POST
      #- http: path: swagger method: GET

